name       : pygraphviz
version    : '1.5'
release    : 7
source     :
    - https://github.com/pygraphviz/pygraphviz/archive/pygraphviz-1.5.tar.gz : 58c3122c7efb9a62275a915953818acd5b3e113b943075501d316ab2291dc21d
homepage   : https://pygraphviz.github.io/
license    : BSD-3-Clause
component  : programming.python
summary    : Python interface to Graphviz graph drawing package
description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and visualization package
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(libpathplan)
setup      : |
    %python3_setup
install    : |
    %python3_install
