name       : pygraphviz
version    : '1.9'
release    : 12
source     :
    - https://github.com/pygraphviz/pygraphviz/archive/pygraphviz-1.9.tar.gz : 885582fa50baf75a9776e45bd14cdfd65c412a2a94f60e8a993649dad5561c43
homepage   : https://pygraphviz.github.io/
license    : BSD-3-Clause
component  : programming.python
summary    : Python interface to Graphviz graph drawing package
description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and visualization package
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(libpathplan)
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
