name       : pygraphviz
version    : '1.5'
release    : 4
source     :
    - https://github.com/pygraphviz/pygraphviz/archive/pygraphviz-1.5.tar.gz : 58c3122c7efb9a62275a915953818acd5b3e113b943075501d316ab2291dc21d
license    : BSD-3-Clause
component  : programming.python
summary    : Python interface to Graphviz graph drawing package
description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and visualization package
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
    - pkgconfig(libpathplan)
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
