name       : pygraphviz
version    : '1.7'
release    : 8
source     :
    - https://github.com/pygraphviz/pygraphviz/archive/pygraphviz-1.7.tar.gz : 9dba480cf9b13cf90e7ef43070b1c8445fb52cd7f27a305ab2b6fe0c100fd768
homepage   : https://pygraphviz.github.io/
license    : BSD-3-Clause
component  : programming.python
summary    : Python interface to Graphviz graph drawing package
description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and visualization package
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(libpathplan)
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
