name       : pygraphviz
version    : '1.8'
release    : 11
source     :
    - https://github.com/pygraphviz/pygraphviz/archive/pygraphviz-1.8.tar.gz : 29e3c7f74687416cca4e279632f5ae7ecd80a0fdc601818fddc7ffc536800aae
homepage   : https://pygraphviz.github.io/
license    : BSD-3-Clause
component  : programming.python
summary    : Python interface to Graphviz graph drawing package
description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and visualization package
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(libpathplan)
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
